/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly PUBLIC_AUTH_URL: string
  readonly PUBLIC_API_URL: string
  readonly PUBLIC_ZERO_URL: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}